function ctrl = init_ctrl()

	% Sample count for simulation
	% Default: 100000 samples (1 second at 100 kHz)
	% Increase for better frequency resolution or longer Allan deviation
	% Decrease for faster simulation during development
	ctrl.N = 2^21;
    
	% Signal bandwidth for analysis [Hz]
	% Typical gyroscope signal bandwidth: 100-200 Hz
	% Used for integrated noise calculations and spectral analysis
	ctrl.fb = 800;
    
	% Plotting flags
	% Set to 1 to enable, 0 to disable
	% Useful during development but disable for batch processing
    
	% Plot drive channel spectra
	% Includes: drive C/V noise, phase integrator, VCO phase noise
	ctrl.plot_spectra_d = false;
    
	% Plot sense channel spectra  
	% Includes: sense C/V noise, rate integrator, total noise at various points
	ctrl.plot_spectra_s = false;
    
	% Plot FFT in spectrum analysis functions
	% Creates detailed spectral plots for each noise source
	ctrl.plot_fft = false;
    
	% Calculate Allan deviation
	% Set to true to calculate Allan deviation for all axes
	% WARNING: Can be time-consuming for large N
	% Recommend: Enable only when needed for stability analysis
	ctrl.calc_adev = true;
    
	% Advanced control parameters (optional)
    
	% Enable detailed logging
	ctrl.verbose = true;
    
	% Save intermediate results
	ctrl.save_intermediate = true;
    
	% Random seed for reproducibility
	% Set to specific value (e.g., 12345) for reproducible results
	% Set to 0 or 'shuffle' for different results each run
	ctrl.random_seed = 12345;
    
	% Temperature for thermal noise calculations
	% Override IMU temperature if needed
	% Set to NaN to use IMU.temperature
	ctrl.temperature_override = NaN;
    
	% Enable RTN modeling (if implemented in sim_sense_noise)
	% Requires additional parameters in IMU structure
	ctrl.enable_rtn = false;
    
	% RTN parameters (used if enable_rtn = 1)
	if ctrl.enable_rtn
		ctrl.rtn.num_traps = 3;
		ctrl.rtn.amplitude = [1.5e-3, 2.0e-3, 1.2e-3];  % [V]
		ctrl.rtn.tau_high = [15e-6, 30e-6, 80e-6];      % [s]
		ctrl.rtn.tau_low = [12e-6, 25e-6, 70e-6];       % [s]
		ctrl.rtn.seed = 42;
	end
    
	% Frequency resolution for spectral analysis
	% Number of points for pwelch() FFT
	% Set to [] for automatic (length/8)
	ctrl.nfft = [];
    
	% Window function for spectral analysis
	% Options: 'hann', 'hamming', 'blackman', 'rectwin'
	ctrl.window = 'hann';
    
	% Overlap for pwelch() [samples or fraction]
	% Set to [] for default 50% overlap
	ctrl.overlap = [];
    
	% Note: Time vector (ctrl.t) is generated by noise_model constructor
	% Note: Noise selection function (ctrl.noise_sel) is set by constructor
    
	% Print configuration if called standalone
	if nargout == 0
		print_ctrl_info(ctrl);
	end
end

function print_ctrl_info(ctrl)
	% PRINT_CTRL_INFO - Display control parameter information
    
	fprintf('\n');
	fprintf('=== Noise Model Control Parameters ===\n');
	fprintf('Simulation:\n');
	fprintf('  Samples (N):            %d\n', ctrl.N);
	fprintf('  Signal bandwidth (fb):  %d Hz\n', ctrl.fb);
	fprintf('\n');
	fprintf('Plotting:\n');
	fprintf('  Drive spectra:          %s\n', bool2str(ctrl.plot_spectra_d));
	fprintf('  Sense spectra:          %s\n', bool2str(ctrl.plot_spectra_s));
	fprintf('  FFT plots:              %s\n', bool2str(ctrl.plot_fft));
	fprintf('\n');
	fprintf('Analysis:\n');
	fprintf('  Calculate Allan dev:    %s\n', bool2str(ctrl.calc_adev));
	fprintf('  Verbose output:         %s\n', bool2str(ctrl.verbose));
	fprintf('\n');
	fprintf('Advanced:\n');
	fprintf('  Random seed:            ');
	if ctrl.random_seed == 0
		fprintf('Random (different each run)\n');
	else
		fprintf('%d (reproducible)\n', ctrl.random_seed);
	end
	fprintf('  Temperature override:   ');
	if isnan(ctrl.temperature_override)
		fprintf('Use IMU temperature\n');
	else
		fprintf('%.1f K\n', ctrl.temperature_override);
	end
	fprintf('  RTN modeling:           %s\n', bool2str(ctrl.enable_rtn));
	if ctrl.enable_rtn
		fprintf('    Number of traps:      %d\n', ctrl.rtn.num_traps);
		fprintf('    Amplitudes:           [%.2f, %.2f, %.2f] mV\n', ...
				ctrl.rtn.amplitude*1000);
	end
	fprintf('\n');
	fprintf('To modify these parameters, edit init_ctrl.m\n');
	fprintf('======================================\n\n');
end

function str = bool2str(val)
	% BOOL2STR - Convert boolean to enabled/disabled string
	if val
		str = 'Enabled';
	else
		str = 'Disabled';
	end
end
